# Generated by Django 3.2 on 2022-10-10 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=254)),
                ('product_sku', models.CharField(blank=True, max_length=254, null=True)),
                ('product_slug', models.SlugField(max_length=254, unique=True)),
                ('product_description', models.TextField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
